runMode: debug
server:
    port: 8091
    readTimeout: 60
    writeTimeout: 60
database:
    type: mysql
    user: root
    password: root
    host: 127.0.0.1
    dbName: ylxs
log:
    path: runtime/log
    prefix: log_
yzj:
    appID: 500000006
    secret: sbLfxVQjBJUm0IRJAQTJ
    eID: 18980581
    yzjServer: https://oa.smart-yulong.com
    pubID: XT-ab62dab1-a6a5-4417-8a00-282fb591a6e3
    pubSecret: e260778b40a9036f8fb4fecfed8e9134
    taskRoleId:  2d7e3698-eec8-4850-8ffa-049ebcdf3825
app:
    UIURL: http://10.132.26.182:3000
    SavePath: upload
    RuntimePath : ./runtime
    cron: 0 0 9 * * ?
    RemindDays: 1
    

