runMode: debug
server:
    port: 8091
    readTimeout: 60
    writeTimeout: 60
database:
    type: mysql
    user: root
    password: 123456
    host: 127.0.0.1
    dbName: ylxs
log:
    path: runtime/log
    prefix: log_
yzj:
    appID: 500000044
    secret: HKJWb2k5c88aqjjbOCdB
    eID: 17802920
    yzjServer: https://yunzhi.cyats.com

