runMode: release
server:
    port: 8091
    readTimeout: 60
    writeTimeout: 60
database:
    type: mysql
    user: root
    password: 123456
    host: mysql
    dbName: ylxs
log:
    path: runtime/log
    prefix: log_
yzj:
    appID: 500000006
    secret: sbLfxVQjBJUm0IRJAQTJ
    eID: 18980581
    yzjServer: https://oa.smart-yulong.com
    pubID: XT-ab62dab1-a6a5-4417-8a00-282fb591a6e3
    pubSecret: e260778b40a9036f8fb4fecfed8e9134
app:
    UIURL: http://119.62.184.109:8082/task-mobile/
    SavePath: upload
    RuntimePath : ./runtime
    corn: 0 0 9 * * ?
